server:
  port: 7001

spring:
  application:
    name: oj-system
  datasource:
    url: jdbc:mysql://129.211.1.222:3306/ojdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: chenQi@2024